resources:
- name: my-application
  type: git
  source:
    branch: master
    uri: https://github.com/sbalashevich/mydemoapp

jobs:
- name: unit-tests
  plan:
  - get: my-application
    trigger: true     
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: maven}
      inputs:
          - name: my-application
      outputs:
          - name: compiled-files
      run:
        path: my-application/ci/run_test
